### ISSUE TITLE
Unhandled exception - unexpected '=>' (T_DOUBLE_ARROW) when using cli to add/list resources

### ISSUE THREAD

**Issue by svoeth** [nextcloud/calendar_resource_management#49]
I wanted to try the app today.
When i use "php occ calendar-resource:*" i get an unhandled exception error.
It does not matter whether i just try to list ressources or to add them. The error is always the same.
Using NC 23.0.4 app is listed as enabled in NC
PHP 7.4.28 , APCu cache enabled (hence the flag `--define apc.enable_cli=1`), Opcache enabled, using redis.

```
www-data@nextcloud:~/nextcloud$ php --define apc.enable_cli=1 occ calendar-resource:list
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /var/www/nextcloud/apps/passwords/lib/Services/HelperService.php:117
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(112): ReflectionClass->__construct()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#12 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#13 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#16 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#19 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#20 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#22 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#23 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#26 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#27 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#28 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#29 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#31 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#32 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#33 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#34 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#35 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#36 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#37 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#38 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#39 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#40 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#41 /var/www/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#42 /var/www/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#43 /var/www/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#44 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#45 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

**Comment by koelle25** [comment]
This error actually comes from the `passwords` app, as can be seen in line 3 of your log (`ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /var/www/nextcloud/apps/passwords/lib/Services/HelperService.php:117`).

Maybe try temporarily disabling this app and executing the command again. If it succeeds you should instead open an issue over on https://git.mdns.eu/nextcloud/passwords

**Comment by svoeth** [comment]
ok, solved it myself

Was using php8.0 on apache already, but forgot to switch to 8.0 in cli...
